<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>nrm</string>
    </array>
    <key>keyEquivalent</key>
    <string>^~C</string>
    <key>name</key>
    <string>Nirum</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>//[^\r\n]*$</string>
            <key>name</key>
            <string>comment.line.double-slash.nirum</string>
        </dict>
        <dict>
            <key>match</key>
            <string>#[^\r\n]*$</string>
            <key>name</key>
            <string>comment.block.documentation.nirum</string>
        </dict>
        <dict>
            <key>match</key>
            <string>@\s*([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)(?:\s*\(("(?:[^"]|\\.)*")\))?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.modifier.annotation.nirum</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.nirum</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>string.quoted.annotation-argument.nirum</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(enum|record|union|service)\s+([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)(?:\s*(/)\s*([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*))?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.type-declaration.nirum</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.nirum</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.behind-name.nirum</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.behind-name.nirum</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(unboxed|import)\s+([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)(?:\s*(/)\s*([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*))?\s*\(\s*([^)]+)\s*\)\s*;</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.type-declaration.nirum</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.nirum</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.behind-name.nirum</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.behind-name.nirum</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.nirum</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(type)\s+([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)\s*=\s*([^;]+)\s*;</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.type-declaration.nirum</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.nirum</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.nirum</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(throws)\s+([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.throws.nirum</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.nirum</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>([|=])\s*([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.tag-separator.nirum</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.nirum</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>\b([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)\s+([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)\s*\(</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.nirum</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.nirum</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>\b([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)(\?)?\s+([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)(?:\s*(/)\s*([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*))?\s*(?:[,);]|$)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.nirum</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.option.nirum</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.other.attribute-name.nirum</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.behind-name.nirum</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>entity.other.attribute-name.behind-name.nirum</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>(bigint|decimal|(?:int|float)(?:32|64)|text|binary|date(?:time)?|bool|uuid|uri)\s*(\?)?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.nirum</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.option.nirum</string>
                </dict>
            </dict>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.nirum</string>
    <key>uuid</key>
    <string>D3BD7ACA-E12F-4CF2-BE55-8CD2743B8FEF</string>
</dict>
</plist>
